version: '3.8'  # Specify the Docker Compose file version

services:
  wildfly:
    image: ghcr.io/marcel-gepardec/api-demo:latest
    networks:
      - api-demo-network
    ports:
      - "8080:8080"  # Map port 80 in the container to port 8080 on the host (adjust as needed)

  db:
    image: mysql:8.1.0
    networks:
      - api-demo-network
    ports:
      - "3306:3306"  # Map port 80 in the container to port 8080 on the host (adjust as needed)
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set the root password for MySQL
      MYSQL_DATABASE: ApiDemo  # Create a database named 'ApiDemo'
      MYSQL_USER: TEST  # Create a user with the specified username
      MYSQL_PASSWORD: password  # Set the password for the user
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      - V0_9_0__initial_db_creation.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

networks:
  api-demo-network:
    driver: bridge

volumes:
  db_data: