--SFC_UID:         00_09_00
--SFC_SCRIPTNAME:  00_09_00_initial_db_create.sql
--SFC_VERSION:     00_09_00

CREATE SEQUENCE SEQ_BENUTZER START WITH 1 INCREMENT BY 1;


CREATE TABLE BENUTZER
(
    ID          NUMBER(20) DEFAULT SEQ_BENUTZER.nextval PRIMARY KEY,
    EMAIL       VARCHAR2(2000) NOT NULL,
    PASSWORD    VARCHAR2(2000) NOT NULL,
    CONSTRAINT BENUTZER_UNIQUE UNIQUE (EMAIL)
);